Solware-Agency/panelweb

- src/features/dashboard/cases/MainCases.tsx
- src/features/dashboard/layouts/Header.tsx
- src/features/dashboard/layouts/Layout.tsx
- src/features/dashboard/layouts/Sidebar.tsx
- src/features/dashboard/reports/ReportsPage.tsx
- src/shared/components/cases/CasesTable.tsx
- Remove unused imports across dashboard components
- Streamline action buttons styling and logic
- Add dark mode toggle functionality to sidebar
- Implement logout feature in sidebar
- Improve sidebar component organization
Components affected:
- DashboardLayout
- Sidebar
- ActionButton
- ThemeToggle
> refactor(dashboard): clean up components and enhance sidebar

- src/shared/components/cases/CaseDetailPanel.tsx
- src/shared/components/cases/CasesTable.tsx
- src/shared/components/cases/EditCaseModal.tsx
- src/shared/components/ui/toast.tsx
1. Login y estado pendiente
Solucionamos que el login no muestre error si el usuario está en estado "pendiente" en la tabla profiles.
Ajustamos el flujo para que, tras el login exitoso, el usuario sea redirigido automáticamente a /pending-approval usando el hook useSecureRedirect, sin mostrar mensajes de error.
3. Validación de pagos al editar un caso
Agregamos una validación en el modal de edición de casos (EditCaseModal.tsx) para que:
No se permita guardar si la suma de los pagos excede el monto total del caso.
Se muestre un mensaje de error si esto ocurre.
4. Toasts siempre visibles sobre los modales
Aumentamos el z-index del contenedor de toasts (ToastViewport) para que los mensajes de error y notificaciones siempre se muestren por encima de cualquier modal.
5. Validación inteligente …
> Enhance CaseDetailPanel and EditCaseModal

- src/features/dashboard/home/MainHome.tsx
- src/features/form/components/payment/PaymentMethodsList.tsx
- src/shared/components/cases/CaseDetailPanel.tsx
- src/shared/components/cases/CasesTable.tsx
- src/shared/components/cases/UnifiedCaseModal.tsx
fix: corregir visualización de datos en MainHome, intercambiando casos y ingresos
fix: actualizar etiquetas de estado de pago a "Estatus" en PaymentMethodsList, CaseDetailPanel y UnifiedCaseModal
fix: eliminar ícono de filtro en el componente CasesTable para simplificar la interfaz
> some changes

- src/features/dashboard/cases/MainCases.tsx
- src/features/dashboard/cases/MyCases.tsx
- src/features/dashboard/changelog/ChangelogTable.tsx
- src/features/dashboard/components/ReactionsTable.tsx
- src/features/form/components/RecordsSection.tsx
- src/lib/supabase-service.ts
- src/shared/components/cases/RequestCaseModal.tsx
- supabase/migrations/20250725014945_sunny_cottage.sql
- Implemented useEffect hooks in MainCases, MyCases, ChangelogTable, ReactionsTable, and RecordsSection to subscribe to Supabase channels for real-time updates.
- Invalidate relevant queries on data changes to ensure the UI reflects the latest information.
- Enhanced the handling of deleted records in change logs by modifying the database schema and related functions to preserve audit trails.
- Removed redundant code and improved overall structure for better maintainability.
> Add real-time updates to dashboard components

- src/app/providers/AuthContext.tsx
- src/features/auth/components/NewPasswordForm.tsx
- src/lib/supabase/auth.ts
- src/shared/components/cases/CasesTable.tsx
Added comprehensive storage cleanup during sign-out processes in AuthContext and Supabase auth module. Implemented pagination in CasesTable for improved case management, including controls for items per page and navigation. Updated NewPasswordForm to streamline sign-out after password reset.
> Enhance authentication flow and storage management.

- src/App.tsx
- src/features/auth/other/EmailVerificationNotice.tsx
- src/features/form/pages/Form.tsx
- src/shared/hooks/useUserProfile.ts
Refactor EmailVerificationNotice for consistent formatting and improve useUserProfile hook with real-time updates and toast notifications for account approval events.
> Integrate Toaster component into App for enhanced user notifications.

- src/lib/supabase/services/cases.ts
- src/shared/components/cases/StepsCaseModal.tsx
- src/shared/components/cases/UnifiedCaseModal.tsx
- src/shared/types/types.ts
- Introduced new service functions `markCaseAsPending` and `approveCaseDocument` for handling case status updates in the Supabase database.
- Updated `StepsCaseModal` component to include steps for marking cases as completed and approving documents, with appropriate UI elements and state management.
- Enhanced real-time synchronization of document approval status and URL updates using Supabase's real-time capabilities.
- Modified `UnifiedCaseModal` and type definitions to accommodate the new `doc_aprobado` field for better data handling across components.
> Add case management functionality with document approval workflow

- src/features/dashboard/cases/MainCases.tsx
- src/features/form/components/RecordsSection.tsx
- src/shared/components/Sidebar.tsx
- src/shared/components/cases/CasesTable.tsx
- src/shared/components/cases/StepsCaseModal.tsx
- src/shared/components/cases/UnifiedCaseModal.tsx
- src/shared/components/ui/calendar.tsx
- Added a new filter for document approval status (`doc_aprobado`) in the MainCases and RecordsSection components, allowing users to filter cases based on their approval state (faltante, pendiente, aprobado).
- Implemented corresponding state management and UI elements to toggle and display the document approval status.
- Updated the statistics and filtering logic to account for the new approval status, ensuring accurate data representation.
- Refactored related components to maintain consistency and improve user experience.
> Enhance case management with document approval filters

- src/features/dashboard/patients/PatientsList.tsx
- src/features/dashboard/patients/PatientsPage.tsx
- src/shared/components/patients/EditPatientInfoModal.tsx
- src/shared/components/patients/PatientHistoryModal.tsx
- Added real-time subscription to medical records changes in PatientsList and PatientsPage components.
- Updated PatientsList to display age directly from patient data instead of calculating from date of birth.
- Introduced EditPatientInfoModal for editing patient details, including name, phone, email, and age.
- Enhanced PatientHistoryModal to allow editing patient information directly from the history view.
> feat: implement real-time updates and edit patient info modal

- package.json
- pnpm-lock.yaml
- src/App.tsx
- src/app/providers/ThemeProvider.tsx
- src/app/routes/lazy-routes.tsx
- src/features/ChatAI/pages/StandaloneChatPage.tsx
- src/features/ChatAI/ui/ChatButton.tsx
- src/features/ChatAI/ui/ChatModal.tsx
- src/features/dashboard/changelog/StandaloneChangelogPage.tsx
- src/features/form/pages/Form.tsx
- src/main.tsx
- src/shared/components/Sidebar.tsx
- src/shared/components/lazy-components.tsx
- src/shared/components/ui/sonner.tsx
- src/shared/hooks/useDarkMode.ts
- Added a new ChatButton component for initiating chat interactions.
- Implemented a ChatModal for user chat sessions with message handling and streaming.
- Introduced a StandaloneChangelogPage for viewing changelog independently.
- Updated ThemeProvider to migrate old theme settings to a new key in localStorage.
- Enhanced App component to include new routes and components for chat and changelog.
- Updated package.json to include 'react-spinners' for loading indicators.
> feat: integrate chat functionality and theme provider

- src/app/routes/PrivateRoute.tsx
- src/app/routes/lazy-routes.tsx
- src/shared/components/Sidebar.tsx
- Introduced ReceptionistHomePage component with lazy loading.
- Updated PrivateRoute to redirect employees to the new home page.
- Modified Sidebar to include a link to the ReceptionistHomePage.
> feat: add ReceptionistHomePage and update routing

- src/features/dashboard/home/ReceptionistHomePage.tsx
- Changed transition effects from 'transition-all' to 'transition-transform' for improved performance and smoother animations on button hover states.
> refactor: update button hover effects in ReceptionistHomePage

- src/features/dashboard/home/ReceptionistHomePage.tsx
- src/features/employee/layouts/EmployeeLayout.tsx
- Actualizada la descripción del botón de formulario.
- Ajustados los márgenes y tamaños de texto para un diseño más compacto y consistente.
- Modificados los efectos de hover y el espaciado en la cuadrícula de navegación.
> refactor: mejorar diseño y texto en ReceptionistHomePage

- src/lib/registration-service.ts
- Eliminated the hardcoded 'Pendiente' status in the prepareRegistrationData function to allow for more flexible status handling based on payment conditions.
> refactor: remove default status from registration data preparation

- src/features/dashboard/cases/MyCases.tsx
- src/lib/medical-cases-service.ts
- src/lib/patients-service.ts
- src/lib/registration-service.ts
- src/lib/supabase-service.ts
- src/shared/components/cases/CaseDetailPanel.tsx
- src/shared/components/cases/CasesTable.tsx
- src/shared/components/cases/UnifiedCaseModal.tsx
- src/shared/components/cases/status.ts
- src/shared/components/patients/EditPatientInfoModal.tsx
- src/shared/components/patients/PatientHistoryModal.tsx
- src/shared/hooks/useDashboardStats.ts
- src/shared/hooks/usePatientAutofill.ts
- src/shared/types/types.ts
- Replaced the use of the 'medical_cases_with_patient' view with direct queries to 'medical_records_clean' and 'patients' tables for improved data retrieval.
- Updated the MyCases and PatientHistoryModal components to filter and display cases based on the new data structure.
- Refactored the getCasesWithPatientInfo function to transform data into the new MedicalCaseWithPatient format.
- Adjusted patient age handling to store as a string with unit (AÑOS/MESES) instead of a number.
- Cleaned up type definitions and ensured compatibility across the application.
> refactor: update medical case handling and patient data structure

- components.json
- src/assets/lib/utils.ts
- src/features/ChatAI/pages/StandaloneChatPage.tsx
- src/features/ChatAI/ui/ChatModal.tsx
- src/shared/components/ui/loader.tsx
- Introduced a new configuration file `components.json` for component management.
- Added utility functions in `utils.ts` for class name merging.
- Replaced `SyncLoader` with a custom `LoaderOne` component in `StandaloneChatPage` and `ChatModal` for improved loading animations.
- Created `LoaderOne` component with motion effects for enhanced user experience.
> feat: add new components and loader implementation

- src/shared/components/cases/CasesTable.tsx
- src/shared/components/cases/FiltersModal.tsx
- src/shared/components/ui/custom-dropdown.tsx
- Introduced a new FiltersModal component to allow users to apply advanced filters for cases, including status, branch, date, and doctor filters.
- Updated CasesTable to integrate the FiltersModal, replacing the previous inline filter controls for a cleaner UI.
- Added temporary state management for filter values to facilitate user interactions without immediate updates to the main filter state.
- Enhanced CustomDropdown to support modal positioning and improved event handling for better user experience.
> feat: implement FiltersModal V.1 for enhanced case filtering in CasesTable

- src/shared/components/ui/custom-dropdown.tsx
- Updated event listeners to only activate when the dropdown is open, enhancing performance.
- Prevented dropdown from closing when clicking inside the dropdown or on the trigger.
- Adjusted scroll event listener to use passive mode for better performance.
- Minor styling adjustments for z-index consistency.
> refactor: improve event handling and dropdown behavior in CustomDropdown

- src/lib/download-utils.ts
- src/shared/components/cases/StepsCaseModal.tsx
- src/shared/hooks/useHandleTransformToPDF.ts
- Introduced a new module `download-utils.ts` with functions to determine production environment, generate appropriate download URLs, and validate download URLs.
- Updated `StepsCaseModal` and `useHandleTransformToPDF` to utilize the new `getDownloadUrl` function for improved PDF retrieval logic.
> feat: add download utilities for PDF handling

- src/lib/download-utils.ts
- Updated the isValidDownloadUrl function to use Boolean for clearer intent and improved readability.
- Ensured the function still checks for valid URLs starting with 'http' or '/api/'.
> refactor: simplify URL validation logic in isValidDownloadUrl function

- api/download-pdf.js
- Added console logging for incoming requests and database responses to aid in debugging.
- Improved error handling for database fetch errors and token mismatches, providing clearer diagnostic messages.
- Removed unnecessary JOIN in the database query to simplify data retrieval.
> feat: enhance logging and error handling in PDF download API

- src/shared/components/Sidebar.tsx
- src/shared/components/cases/UnifiedCaseModal.tsx
- src/shared/components/ui/dialog.tsx
- Replaced the Folder icon with Microscope in the Sidebar component for better representation.
- Updated the icon for the Análisis section to FolderSearch for improved clarity.
- Introduced a helper function in UnifiedCaseModal to format payment methods with the correct currency symbol, enhancing the display of payment information.
> refactor: update Sidebar icons and enhance payment method formatting

- src/features/form/components/PatientDataSection.tsx
- src/features/form/components/ServiceSection.tsx
- src/features/form/components/payment/PaymentHeader.tsx
- src/features/form/components/payment/PaymentMethodItem.tsx
- src/shared/components/cases/UnifiedCaseModal.tsx
- src/shared/components/ui/form-dropdown.tsx
@- Added unique IDs to various form inputs across components including PatientDataSection, ServiceSection, PaymentHeader, PaymentMethodItem, and UnifiedCaseModal to enhance accessibility and improve form handling.
> refactor: add unique IDs to form inputs for better accessibility

- src/features/dashboard/changelog/ChangelogTable.tsx
- src/features/dashboard/home/MainHome.tsx
- src/features/dashboard/patients/PatientsList.tsx
- src/features/dashboard/settings/SessionTimeoutSettings.tsx
- src/features/dashboard/stats/StatsPage.tsx
- src/shared/components/cases/CasesTable.tsx
- src/shared/components/cases/DoctorFilterPanel.tsx
- src/shared/components/cases/FiltersModal.tsx
- src/shared/components/cases/Pagination.tsx
- src/shared/components/patients/EditPatientInfoModal.tsx
- src/shared/components/patients/PatientHistoryModal.tsx
- Se agregó una función para traducir nombres de campos del inglés al español en el componente ChangelogTable.
- Se actualizaron las etiquetas de los campos en la visualización de cambios para mostrar las traducciones correspondientes.
- Se mejoró la presentación de los valores antiguos y nuevos en el registro de cambios.
> refactor: mejorar la traducción de etiquetas de campos en ChangelogTable

- src/features/dashboard/users/MainUsers.tsx
- src/lib/medical-cases-service.ts
- src/lib/supabase/services/cases.ts
- src/lib/supabase/services/getAndSyncUserProfile.ts
- src/shared/components/cases/StepsCaseModal.tsx
- src/shared/hooks/useDashboardStats.ts
- src/shared/types/types.ts
- Added role, created_at, updated_at, and estado properties to user profiles for better data integrity.
- Introduced cito_status to MedicalCase interfaces and related services to track cytological status.
- Implemented positive and negative case document handling functions in the cases service.
- Updated StepsCaseModal to include logic for handling positive and negative case statuses, improving user interaction and workflow.
> refactor: enhance user and medical case handling

- src/shared/components/Sidebar.tsx
- Temporarily commented out the NavItem for "Mis Casos" in the Sidebar component to streamline the navigation options. This change is part of ongoing adjustments to improve user experience and interface clarity.
> refactor: comment out NavItem in Sidebar component
